import { Category } from "../types/category";
import { Expense } from "../types/expense";
import { ExpensesGroup } from "../types/expensesGroup";
import { Recurrence } from "../types/recurrence";
export const categories: Category[] = [
  { _id: "1", name: "Transportation", color: "#FF0000" },
  { _id: "2", name: "Food", color: "#00FF00" },
  { _id: "3", name: "Shopping", color: "#0000FF" },
  { _id: "4", name: "Housing", color: "#FFFF00" },
  { _id: "5", name: "Entertainment", color: "#00FFFF" },
  { _id: "6", name: "Utilities", color: "#FF00FF" },
  { _id: "7", name: "Category 7", color: "#C0C0C0" },
  { _id: "8", name: "Category 8", color: "#808080" },
  { _id: "9", name: "Category 9", color: "#800000" },
  { _id: "10", name: "Category 10", color: "#008000" },
];

// export const dummyExpenses: Expense[] = [
//   {
//     _id: "1",
//     amount: 6,
//     recurrence: Recurrence.None,
//     date: new Date("2023-04-22"),
//     note: "Lunch at McDonald's",
//     category: categories[0],
//   },
//   {
//     _id: "2",
//     amount: 0,
//     recurrence: Recurrence.Weekly,
//     date: new Date("2023-04-23"),
//     note: "Gasoline for car",
//     category: categories[1],
//   },
//   {
//     _id: "3",
//     amount: 4,
//     recurrence: Recurrence.None,
//     date: new Date("2023-04-20"),
//     note: "Spotify subscription",
//     category: categories[2],
//   },
//   {
//     _id: "4",
//     amount: 6,
//     recurrence: Recurrence.Monthly,
//     date: new Date("2023-04-15"),
//     note: "Movie ticket",
//     category: categories[3],
//   },
//   {
//     _id: "5",
//     amount: 5,
//     recurrence: Recurrence.Yearly,
//     date: new Date("2023-12-29"),
//     note: "New Year's Eve party",
//     category: categories[4],
//   },
// ];

export const dummyExpenseGroups: ExpensesGroup[] = [
  {
    day: "2023-03-22",
    expenses: [
      {
        _id: "1",
        amount: 10.5,
        recurrence: Recurrence.None,
        date: new Date("2023-04-22"),
        note: "Lunch at McDonald's",
        category: {
          _id: "1",
          color: "#FF0000",
          name: "Food",
        },
      },
      {
        _id: "6",
        amount: 35.0,
        recurrence: Recurrence.None,
        date: new Date("2023-04-22"),
        note: "Groceries",
        category: {
          _id: "4",
          color: "#FFFF00",
          name: "Shopping",
        },
      },
    ],
    total: 45.5,
  },
  {
    day: "2023-01-22",
    expenses: [
      {
        _id: "2",
        amount: 20.0,
        recurrence: Recurrence.Weekly,
        date: new Date("2023-04-23"),
        note: "Gasoline for car",
        category: {
          _id: "2",
          color: "#0000FF",
          name: "Transportation",
        },
      },
      {
        _id: "7",
        amount: 10.99,
        recurrence: Recurrence.None,
        date: new Date("2023-04-23"),
        note: "Coffee with friends",
        category: {
          _id: "3",
          color: "#008000",
          name: "Entertainment",
        },
      },
    ],
    total: 30.99,
  },
  {
    day: "2023-04-22",
    expenses: [
      {
        _id: "1",
        amount: 10.5,
        recurrence: Recurrence.None,
        date: new Date("2023-04-22"),
        note: "Lunch at McDonald's",
        category: {
          _id: "1",
          color: "#FF0000",
          name: "Food",
        },
      },
      {
        _id: "6",
        amount: 35.0,
        recurrence: Recurrence.None,
        date: new Date("2023-04-22"),
        note: "Groceries",
        category: {
          _id: "4",
          color: "#FFFF00",
          name: "Shopping",
        },
      },
    ],
    total: 45.5,
  },
  {
    day: "2023-04-28",
    expenses: [
      {
        _id: "2",
        amount: 20.0,
        recurrence: Recurrence.Weekly,
        date: new Date("2023-04-23"),
        note: "Gasoline for car",
        category: {
          _id: "2",
          color: "#0000FF",
          name: "Transportation",
        },
      },
    ],
    total: 30.99,
  },
  {
    day: "2023-05-01",
    expenses: [
      {
        _id: "1",
        amount: 10.5,
        recurrence: Recurrence.None,
        date: new Date("2023-04-22"),
        note: "Lunch at McDonald's",
        category: {
          _id: "1",
          color: "#FF0000",
          name: "Food",
        },
      },
      {
        _id: "6",
        amount: 35.0,
        recurrence: Recurrence.None,
        date: new Date("2023-04-22"),
        note: "Groceries",
        category: {
          _id: "4",
          color: "#FFFF00",
          name: "Shopping",
        },
      },
    ],
    total: 45.5,
  },
];

export const dummyExpenses: Expense[] = [
  {
    _id: "0",
    amount: 95,
    recurrence: Recurrence.None,
    date: new Date("2023-05-03T15:09:43.625Z"),
    note: "Expense #1",
    category: categories[0],
  },
  {
    _id: "1",
    amount: 67,
    recurrence: Recurrence.Yearly,
    date: new Date("2023-05-01T15:09:43.625Z"),
    note: "Expense #2",
    category: categories[1],
  },
  {
    _id: "2",
    amount: 47,
    recurrence: Recurrence.Weekly,
    date: new Date("2023-04-30T15:18:22.827Z"),
    note: "Expense #3",
    category: categories[0],
  },
  {
    _id: "3",
    amount: 27,
    recurrence: Recurrence.None,
    date: new Date("2023-03-19T08:01:56.286Z"),
    note: "Expense #4",
    category: categories[2],
  },
  {
    _id: "4",
    amount: 35,
    recurrence: Recurrence.Daily,
    date: new Date("2023-01-26T19:19:47.231Z"),
    note: "Expense #5",
    category: categories[3],
  },
  {
    _id: "5",
    amount: 86,
    recurrence: Recurrence.Yearly,
    date: new Date("2023-04-13T06:02:09.590Z"),
    note: "Expense #6",
    category: categories[0],
  },
  {
    _id: "6",
    amount: 15,
    recurrence: Recurrence.Weekly,
    date: new Date("2023-01-25T12:15:11.325Z"),
    note: "Expense #7",
    category: categories[0],
  },
  {
    _id: "7",
    amount: 71,
    recurrence: Recurrence.Weekly,
    date: new Date("2023-01-21T15:31:33.498Z"),
    note: "Expense #8",
    category: categories[4],
  },
  {
    _id: "8",
    amount: 68,
    recurrence: Recurrence.None,
    date: new Date("2023-02-10T11:07:59.881Z"),
    note: "Expense #9",
    category: categories[3],
  },
  {
    _id: "9",
    amount: 2,
    recurrence: Recurrence.Yearly,
    date: new Date("2023-02-16T09:15:41.331Z"),
    note: "Expense #10",
    category: categories[0],
  },
  {
    _id: "10",
    amount: 58,
    recurrence: Recurrence.None,
    date: new Date("2023-01-09T08:31:44.165Z"),
    note: "Expense #11",
    category: categories[0],
  },
  {
    _id: "11",
    amount: 12,
    recurrence: Recurrence.Yearly,
    date: new Date("2023-03-10T21:25:23.167Z"),
    note: "Expense #12",
    category: categories[0],
  },
  {
    _id: "12",
    amount: 76,
    recurrence: Recurrence.Monthly,
    date: new Date("2023-03-19T00:00:19.546Z"),
    note: "Expense #13",
    category: categories[4],
  },
  {
    _id: "13",
    amount: 63,
    recurrence: Recurrence.Weekly,
    date: new Date("2023-01-14T13:08:16.873Z"),
    note: "Expense #14",
    category: categories[0],
  },
  {
    _id: "14",
    amount: 65,
    recurrence: Recurrence.None,
    date: new Date("2023-02-11T13:22:36.970Z"),
    note: "Expense #15",
    category: categories[3],
  },
  {
    _id: "15",
    amount: 21,
    recurrence: Recurrence.None,
    date: new Date("2023-04-03T20:23:21.848Z"),
    note: "Expense #16",
    category: categories[0],
  },
  {
    _id: "16",
    amount: 32,
    recurrence: Recurrence.Monthly,
    date: new Date("2023-04-20T14:10:21.888Z"),
    note: "Expense #17",
    category: categories[5],
  },
  {
    _id: "17",
    amount: 85,
    recurrence: Recurrence.None,
    date: new Date("2023-03-28T14:31:04.461Z"),
    note: "Expense #18",
    category: categories[3],
  },
  {
    _id: "18",
    amount: 4,
    recurrence: Recurrence.Weekly,
    date: new Date("2023-03-13T14:52:53.008Z"),
    note: "Expense #19",
    category: categories[4],
  },
  {
    _id: "19",
    amount: 59,
    recurrence: Recurrence.None,
    date: new Date("2023-02-23T18:15:42.941Z"),
    note: "Expense #20",
    category: categories[4],
  },
];
